<a href="https://colab.research.google.com/github/eggshell-coder/Machine-learning-topic-for-learning-/blob/main/LinearRegression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()


Saving carprices.csv to carprices.csv


In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn import linear_model
df=pd.read_csv('/content/carprices.csv')

In [3]:
df.head()

Mileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500

In [4]:
df.isnull().sum()

Mileage          0
Age(yrs)         0
Sell Price($)    0
dtype: int64

In [ ]:

median_bedrooms=df.bedrooms.median()
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
X=df.drop('Sell Price($)',axis='columns')
y=df['Sell Price($)']

In [7]:
X

Mileage  Age(yrs)
0     69000         6
1     35000         3
2     57000         5
3     22500         2
4     46000         4
5     59000         5
6     52000         5
7     72000         6
8     91000         8
9     67000         6
10    83000         7
11    79000         7
12    59000         5
13    58780         4
14    82450         7
15    25400         3
16    28000         2
17    69000         5
18    87600         8
19    52000         5

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [9]:
len(X_train)

14

In [10]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [13]:
clf.predict(X_test)

array([27671.59496208, 16335.06897558, 37679.56656213, 30156.50361377,
       25946.199655  , 20355.57945057])

In [15]:
clf.score(X_test,y_test)

0.8313620974156793

In [ ]:
reg.predict(x_train)

array([810000., 610000., 760000., 595000.])

In [ ]:
import pickle
with open('reg_pickle','wb') as f:
  pickle.dump(reg,f)

In [ ]:
with open('reg_pickle','rb') as f:
  sreg=pickle.load(f)

In [ ]:
sreg.predict([[3000,3,30]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([525597.01492537])